osd:
  cluster:
    nodeid: "1"
    clusterid: "rodriguise"
  drivers:
#   vfs:
#   pwx:
#    nfs:
#      server: "127.0.0.1"
#      path: "/nfs"
#    btrfs:
#      home: "/var/lib/openstorage/btrfs"
#    aws:
#      AWS_ACCESS_KEY_ID: your_access_key
#      AWS_SECRET_ACCESS_KEY: your_secret_access_key
    #buse:
    coprhd:
        url: "https://172.31.32.189:4443/"
        token: "BAAcZTdIT2dLUDJ1OGtHMTY0QjduWmhLc1Y3c1QwPQMAZwQAG3Byb3h5VG9rZW5TaWduYXR1cmVLZXlFbnRyeQIAAQEFAEJ1cm46c3RvcmFnZW9zOlByb3h5VG9rZW46OGY4OGM5NGItNDNlNi00ZDEyLWE3OGUtMWY4NWJmMTRiMDJjOnZkYzECAALQDw=="
        project: "default"
        varray: "default"
        vpool: "default"
        port: "0d7c7cc100000000"
        
  graphdrivers:
    #proxy:
    #layer0:
    #chainfs:
