osd:
  cluster:
    nodeid: "1"
    clusterid: "deadbeeef"
  drivers:
#   vfs:
#   pwx:
#    nfs:
#      server: "127.0.0.1"
#      path: "/nfs"
#    btrfs:
#      home: "/var/lib/openstorage/btrfs"
    #aws:
    #buse:
    coprhd:
        url: "https://<host:port>/"
        token: ""
        project: "<project name>"
        varray: "<varray name>"
        vpool: "<vpool name>"
        port: "<initiator id>"
        
  graphdrivers:
    #proxy:
    #layer0:
    #chainfs:
